#!/bin/sh
# $Id: cifsumount,v 1.3 2010/03/22 01:03:56 friedman Exp $

test ${EUID-`id -u`} -eq 0 || exec sudo "$0" "$@"
umask 022

exitstat=0

case $1 in
    -a ) set :
         while read fs mnt ftype ignrest ; do
             case $ftype in
                 cifs ) set "$@" "$mnt" ;;
             esac
         done < /proc/mounts
         shift ;;
    -* )
        echo "cifsumount: Unrecognized option \"$1\"" 1>&2
        exit 1 ;;
esac

for vol in "$@"; do
    case $vol in
        //* )  vol=/s/${vol#//} ;;
        *:/* ) vol=/s/${vol%:*}${vol#*:} ;;
    esac
    umount -v "$vol" || exitstat=$?
done

{ find /s -xdev -type d -print0 | sort -rz | xargs -0 rmdir; } 2> /dev/null

exit $exitstat

# eof
