#!/bin/sh
# $Id: cifsumount,v 1.2 2009/04/08 00:30:51 friedman Exp $

test `id -u` -eq 0 || exec sudo "$0" ${1+"$@"}
umask 022

exitstat=0

case $1 in
  -a ) umount -t cifs -av ;;
  -* )
    echo "cifsumount: Unrecognized option \"$1\"" 1>&2
    exit 1 ;;
  * )
    for vol in ${1+"$@"}; do
      case $vol in
        //* )  vol=`echo "$vol" | sed -e 's=^//=/s/='` ;;
        *:/* ) vol=/s/`echo "$vol" | sed -e "s/://"`   ;;
      esac
      umount "$vol" || exitstat=$?
    done ;;
esac

{ find /s -xdev -type d -print0 | sort -rz | xargs -0 rmdir; } 2> /dev/null

exit $exitstat

# eof
