#!/usr/bin/env python3

import argparse
import sys

from nfelfcore import ElfCore


def get_args():
    p = argparse.ArgumentParser()
    p.add_argument( 'core', help='Core file(s)', nargs='+' )
    return p.parse_args()


def main():
    args = get_args()
    for file in args.core:
        core   = ElfCore( file )
        auxv   = core.auxv_dict()
        execfn = auxv[ 'EXECFN' ]

        if len( args.core ) == 1:
            print( execfn )
        else:
            if idx := file.rfind( '/' ) >= 0:
                file = file[ idx: ]
            print( file, execfn, sep=': ' )


if __name__ == '__main__':
    sys.exit( main() )

# eof
