#!/bin/sh
# $Id: cpufreq,v 1.1 2009/05/17 05:50:53 friedman Exp $

# Display current (if no arg), or set new cpu frequency.

sys=/sys/devices/system/cpu

# These are the min/max values which the core is capable of.
#
# The scaling governor can be programmed to use lessor or greater values
# than these, e.g. the max frequency can be capped by writing a new value
# to scaling_max_freq.  This script won't change the scaling maxima/minima,
# so these two core values are just documented here for reference.
#
#read min_freq  < $sys/cpu0/cpufreq/cpuinfo_min_freq
#read max_freq  < $sys/cpu0/cpufreq/cpuinfo_max_freq

read  cur_freq  < $sys/cpu0/cpufreq/scaling_cur_freq
read  cur_min   < $sys/cpu0/cpufreq/scaling_min_freq
read  cur_max   < $sys/cpu0/cpufreq/scaling_max_freq
read  avail     < $sys/cpu0/cpufreq/scaling_available_frequencies

case $1 in
  min* ) new=$cur_min ;;
  max* ) new=$cur_max ;;

  avail* | help ) echo $avail    ; exit 0 ;;
  ''            ) echo $cur_freq ; exit 0 ;;

  * ) # Test to see if specified frequency is allowed.
      case " $avail " in
        *" $1 "* ) new=$1 ;;
        * ) echo Available frequencies: $avail 1>&2 ; exit 1 ;;
      esac ;;
esac

for cpu in $sys/cpu*/cpufreq ; do
  echo $new > $cpu/scaling_max_freq
done

echo $new

# eof
