#!/bin/sh
# $Id$

cd /sys/class/dmi/id || exit $?

for prop in * ; do
    case $prop in
        modalias | power | subsystem | uevent ) continue ;;
    esac

    test -d $prop && continue
    test -r $prop || continue

    read val < $prop
    case $val in '' ) continue ;; esac

    printf "%-18s %s\n" $prop "$val"
done

# eof
