#!/bin/sh
# $Id: firefox,v 1.7 2011/10/10 17:34:45 friedman Exp $

prog=`run-next -p "$0"`

case $* in
    *-ProfileManager* ) exec run-misc.sh "$prog" "$@" ;;
esac

if run-misc.sh "$prog" -remote 'ping()' 2> /dev/null ; then
    exec run-misc.sh "$prog" "$@"
fi

numscreens=`xdpyinfo | sed -n -e '/^number of screens: */s///p'`
case $numscreens in
    1 ) exec run-misc.sh "$prog" "$@" ;;
esac

case $DISPLAY in
    :*.0 ) set fnord -P firefox     "$@"; shift ;;
    :*.1 ) set fnord -P firefox.2nd "$@"; shift ;;
esac

exec run-misc.sh "$prog" "$@"

# eof
