#!/bin/sh

# 2023-10-16
# Setting this to 0 stops firefox from spraying a firehose of glib errors
# to stderr, as a consequence of DBus messages to nonexistent services.
# See a11y::PreInit() in firefox/accessible/atk/Platform.cpp.
#
# If firefox continues to spew in the future because of other DBus traffic,
# consider just unsetting DBUS_SESSION_BUS_ADDRESS.  But as of right now,
# this was the only thing that seemed to be mishandled.
export GNOME_ACCESSIBILITY=0

prog=`run-next -p "$0"`
ffox() { exec run-misc.sh "$prog" "$@"; }

case $* in *-ProfileManager* ) ffox -no-remote "$@" ;; esac

# The profile name 'ffoxq' was based on firefox 57's "quantum" release,
# which was a flag day breaking any extension relying on XUL.
profile=ffoxq

numscreens=`xdpyinfo | sed -n -e '/^number of screens: */s///p'`
case $numscreens$DISPLAY in
    2:*.0 ) ffox -P $profile     "$@" ;;
    2:*.1 ) ffox -P $profile.2nd "$@" ;;
    * ) ffox "$@" ;;
esac

# eof
