#!/bin/bash

: ${GDB:=gdb}

execfn()
{
    if type core-execfn >/dev/null 2>&1; then
        core-execfn "$1"
    else
        file -b "$1" | sed -ne "/.*, execfn: '\(.*\)',.*/s//\1/p"
    fi
}

main()
{
    declare -a gdbargs=( -quiet )

    for arg in "$@"; do
        case ${arg##*/} in
            core* ) core=$arg prog=`execfn "$arg"` ;;
            *     ) gdbargs+=( "$arg" ) ;;
        esac
    done

    case ${core:-notfound} in
        notfound ) echo "No core file specified?" 1>&2; exit 1 ;;
    esac
    case ${prog:-notfound} in
        notfound ) echo "Could not determine executable corresponding to core" 1>&2; exit 1 ;;
    esac

    case $prog in
        */* )
            case $core in
                /* ) : ;;
                *  ) core=$(realpath $PWD/$core) ;;
            esac
            # Using --cd won't enable reading in the .gdbinit
            # file in that directory at startup.
            #gdbargs+=( --cd="${prog%/*}" )
            cd "${prog%/*}" ;;
    esac

    case ${INSIDE_EMACS:+isset} in
        isset ) gdbargs+=( --fullname ) ;;
    esac

    exec $GDB "${gdbargs[@]}" "$prog" "$core"
}

main "$@"

# eof
