#!/bin/bash

# Add -I or --binary-files=without-match skip binary files

options=(--perl-regexp

         --devices=skip
         --directories=recurse

         --line-number
         #--initial-tab

         --exclude='*~'
         --exclude='#*#'
         --exclude='*.elc'
         --exclude='*.[oa]'
         --exclude='*.py[co]'
         --exclude='.#*'
         --exclude='COPYING*'
         --exclude='*LICENSE*'

         --exclude-dir=CVS
         --exclude-dir=RCS
         --exclude-dir=.bzr
         --exclude-dir=.git
         --exclude-dir=.hg
         --exclude-dir=.svn

         #--color=auto
      )

exec grep "${options[@]}" "$@"

# eof
