#!/bin/sh
# $Id: mgrep,v 1.1 2017/06/27 19:07:32 friedman Exp $

# Add -I or --binary-files=without-match skip binary files

options=(--perl-regexp

         --devices=skip
         --directories=recurse

         --line-number
         --initial-tab

         --exclude='*~'
         --exclude='*.elc'
         --exclude='*.[oa]'
         --exclude=COPYING
         --exclude=LICENSE

         --exclude-dir=CVS
         --exclude-dir=.bzr
         --exclude-dir=.git
         --exclude-dir=.hg
         --exclude-dir=.svn

         #--color=auto
      )

exec grep "${options[@]}" "$@"

# eof
