#!/bin/sh
# $Id: mkkmodule,v 1.2 2006/11/21 00:15:47 friedman Exp $

KVERSION=${KVERSION-`uname -r`}

deftarget=modules
for arg in ${1+"$@"}; do
  case $arg in
    *=* ) :                  ;;
    *   ) deftarget= ; break ;;
  esac
done

if [ -f Kconfig ]; then
  set x `sed -e '/^config \(.*\)/!d' -e 's//CONFIG_\1=m/' Kconfig` ${1+"$@"}
  shift
fi

set x ${MAKE-make} -C /lib/modules/$KVERSION/build M=`pwd` $deftarget ${1+"$@"}
shift

echo ${1+"$@"}
exec ${1+"$@"}

# eof
