#!/bin/sh

: ${KVERSION:=`uname -r`}
: ${KROOT:=/lib/modules/$KVERSION/build}

deftarget=modules
for arg in "$@"; do
  case $arg in
    *=* ) :                  ;;
    *   ) deftarget= ; break ;;
  esac
done

if [ -f Kconfig ]; then
  set x `sed -e '/^config \(.*\)/!d' -e 's//CONFIG_\1=m/' Kconfig` "$@"
  shift
fi

set x ${MAKE-make} -C $KROOT M=`pwd` $deftarget "$@"
shift

echo "$@"
exec "$@"

# eof
