#!/bin/sh
# $Id$

${LAST-last} --system --fullnames --hostlast --time-format iso "$@" |
    sed -e 's/\(-[0-9][0-9]\)T\([0-9][0-9]:\)/\1 \2/g' \
        -e 's/-\([0-9][0-9]\):\([0-9][0-9]\)/-\1\2 /g'

# eof
