#!/bin/sh
# $Id: mltrace,v 1.2 2008/01/16 19:16:38 friedman Exp $

help=`${LTRACE-ltrace} --help 2>&1`
case $help in
    *' -C '* ) demangle=-C ;;
esac

exec ${LTRACE-ltrace} $demangle -f -n2 -s 65535 -S -T "$@"

# eof
