#!/bin/sh
# $Id: mstrace,v 1.5 2016/06/08 22:34:16 friedman Exp $

case :${HEX+set}:${hex+set}: in
  *:set:* ) set x -e read=all -e write=all "$@"; shift ;;
esac

set x ${STRACE-strace}   \
         -e abbrev=none  \
         -e signal=all   \
         -e trace=all    \
         -e verbose=all  \
         -s 65535        \
         -S name         \
         -f -v -T -y  \
         "$@"
shift

${MSTRACE_CMD-exec} "$@"

# eof
