#!/bin/sh
# $Id: mtrace,v 1.1 1997/06/19 23:13:18 friedman Exp $

case :${HEX+set}:${hex+set}: in
  *:set:* ) set fnord -e read=all -e write=all ${1+"$@"}; shift ;;
esac

exec strace             \
        -e abbrev=none  \
        -e signal=all   \
        -e trace=all    \
        -e verbose=all  \
        -s 65535        \
        -S name         \
        -F -f -v -T     \
        ${1+"$@"}
