#!/bin/sh
# $Id: nuke-desktop-gui-cruft,v 1.8 2011/11/24 19:37:30 friedman Exp $

procs='
  /^gvfsd/
  /^gvfs-/
  /gnome-.*-daemon/
  gnome-screensaver
  menu-cached
  notification-daemon
  dconf-service
  idn
  aspell
'

extra='
  npviewer.bin
  mozplugger-helper
  plugin-container
'

case $1 in
  -f ) procs="$procs $extra"; shift ;;
esac

exec mkill $procs

# eof
