#!/bin/sh
# $Id: nuke-desktop-gui-cruft,v 1.9 2012/02/12 21:01:04 friedman Exp $

procs='
  /^gvfsd/
  /^gvfs-/
  /gnome-.*-daemon/
  gnome-screensaver
  dconf-service
  gconfd-2
  menu-cached
  notification-daemon
  idn
  aspell
  at-spi-bus-launcher

  evolution-addressbook-factory
  goa-daemon
  libsocialweb-core
  mission-control-5
  telepathy-logger
'

extra='
  npviewer.bin
  mozplugger-helper
  plugin-container
'

case $1 in
  -f ) procs="$procs $extra"; shift ;;
esac

exec mkill $procs

# eof
