#!/bin/sh
# $Id: nuke-desktop-gui-cruft,v 1.4 2011/01/04 13:09:29 friedman Exp $

procs='
  /^gvfsd/
  /^gvfs-/
  /gnome-.*-daemon/
  gnome-screensaver
  notification-daemon
  idn
  aspell
'

exec mkill $procs

# eof
