#!/bin/sh
# $Id$

for arg in "$@"; do
    case $arg in
        --* ) : ;;
        -*q*l* | -*l*q* )
            set : --noartifact --noghost "$@"
            shift
            break ;;
    esac
done

exec run-next "$0" "$@"

# eof
