#!/bin/sh
# $Id: rpm-erase,v 1.1 2010/11/29 06:40:40 friedman Exp $

# Older linux distributions cannot handle 2^17 or more max-chars.
size=65536

case $* in
  *"*"* ) verbose=--verbose ;;
esac

rpm --qf "%{NAME}\n" --nodigest --nosignature -qa "$@" \
 | xargs $verbose \
    --no-run-if-empty \
    --max-args  $size \
    --max-chars $size \
    rpm --erase --allmatches

# eof
