#!/bin/sh

rpmq()
{
  local qf='%{name}-%{version}-%{release}.%{arch}'
  case $1 in
    -qf | --qf ) qf=$2 ; shift 2 ;;
  esac

  rpm --nodigest --nosignature -q --qf "$qf\n" "$@"
}

rpmpkg()
{
  local pkg
  for pkg in "$@" ; do
    case $pkg in
      *\** ) rpmq -a "$pkg" ;;
      * )    rpmq    "$pkg" ;;
    esac
  done
}

rpmsig()
{
  local qf='%|dsaheader?{%{dsaheader:pgpsig}}'
  qf=$qf:'{%|rsaheader?{%{rsaheader:pgpsig}}'
  qf=$qf:'{%|siggpg?{%{siggpg:pgpsig}}'
  qf=$qf:'{%|sigpgp?{%{sigpgp:pgpsig}}'
  qf=$qf:'{(none)}|}|}|}|'
  rpmq -qf "$qf" "$@" | sed 's/.*Key ID.*\(........\)$/\1/'
}

key2dist()
{
  case $1 in
    4f2a6fd2 ) echo fedora-core   ;;
    1ac70ce6 ) echo fedora-extras ;;
    a109b1ec ) echo livna         ;;
    66534c2b ) echo atrpms        ;;
    6b8d79e6 ) echo dag           ;;
    1aa78495 ) echo dries         ;;
    e42d547b ) echo freshrpms     ;;
    ff6382fa ) echo kde-redhat    ;;
    '(none)' ) echo '(unknown)' ;;
    * ) rpmq -qf '%{name}-%{version}-%{release} %{summary}' \
             --whatprovides "gpg($1)" \
         | sed 's/gpg(/(/' ;;
  esac
}

main()
{
  rpmpkg "$@" \
   | sort -u \
   | while read pkg; do
       echo -n $pkg ''
       key2dist `rpmsig "$pkg"`
     done \
   | fmtcols -n 2 -S '  '
}

main "$@"

# eof
