#!/bin/bash
# $Id: screen,v 1.2 2010/06/12 03:19:02 friedman Exp $

SHLVL=0
LC_CTYPE=en_US.UTF-8
export SHLVL LC_CTYPE

terminfodirs="
  $HOME/lib/terminfo
  /usr/share/terminfo
  /usr/lib/terminfo
  /opt/lude/lib/terminfo
"
for d in $terminfodirs; do
  if [ -f $d/s/screen-bce-256color ]; then
    TERMINFO=$d
    export TERMINFO
    break
  fi
done

for screen in /opt/lude/bin/screen /usr/bin/screen ; do
  if [ -x $screen ]; then
    exec -a screen $screen "$@"
  fi
done

exec run-next "$0" "$@"

# eof
