#!/usr/bin/env bash
# screen wrapper

terminfo_dirs=(
    $HOME/lib/terminfo
    /opt/lude/lib/terminfo
)

termtypes=(
    screen-256color-bce
    screen.$TERM
)

screen_prog=(
    /opt/lude/bin/screen
    /usr/bin/screen
)

deffirst()
{
    declare -n var=$1; shift
    case ${var:+isset} in isset ) return 0 ;; esac

    declare file
    for file in "$@"; do
        if [ -e "$file" ]; then
            var=$file
            export var
            return 0
        fi
    done
    return 1
}

deffirst2()
{
    declare -n var=$1; shift
    case ${var:+isset} in isset ) return 0 ;; esac

    declare file=$1; shift
    declare dir
    for dir in "$@"; do
        if [ -e "$dir/$file" ]; then
            var=$dir
            export var
            return 0
        fi
    done
    return 1
}

main()
{
    export LC_CTYPE=en_US.UTF-8
    export SHLVL=0
    export SYSSCREENRC=/dev/null   # don't read /etc/screenrc
    : ${sinit:=$HOME/etc/init}

    deffirst SCREENRC $HOME/.screenrc \
                      $sinit/share/screenrc

    for term in "${termtypes[@]}"; do
        if deffirst2 TERMINFO ${term:0:1}/$term "${terminfo_dirs[@]}"; then
            break
        fi
    done

    for screen in "${screen_prog[@]}" ; do
        if [ -x "$screen" ]; then
            exec -a screen "$screen" "$@"
        fi
    done

    exec run-next "$0" "$@"
}

main "$@"

# eof
