#!/usr/bin/perl -w

# $Id: sensors-monitor,v 1.2 2004/03/01 08:42:10 friedman Exp $

use strict;
use POSIX qw(ctime);

my $c = `tput clear`;

while (1)
  {
    printf ("%s%s\n%s", $c, ctime(time), scalar `sensors -f @ARGV`);
    sleep (60);
  }
