#!/usr/bin/perl -w

# $Id: sensors-monitor,v 1.1 2004/02/02 09:17:12 friedman Exp $

use strict;
use POSIX qw(ctime);

my $c = `tput clear`;

while (1)
  {
    printf ("%s%s\n%s", $c, ctime(time), scalar `sensors -f`);
    sleep (60);
  }
