#!/bin/sh
# $Id: set-dbus-session-env,v 1.3 2017/09/17 22:20:18 friedman Exp $

vars="
    XDG_CACHE_HOME
    XDG_CONFIG_HOME
    XDG_DATA_HOME
    XDG_STATE_HOME
    FREETYPE_PROPERTIES
    PULSE_SCRIPT
    $*
"

havecmd() { type "$@" > /dev/null 2>&1; }

dbuscmd=dbus-update-activation-environment
usedcmd=${DBUS_SESSION_BUS_ADDRESS:+yes}
if havecmd $dbuscmd && [ .$usedcmd = .yes ]; then
    exec $dbuscmd --systemd "$@" $vars
fi

if havecmd systemctl; then
    exec systemctl --user import-environment "$@" $vars
fi

exit 1

# eof
