#!/bin/bash

case $0 in
  */uc[gc]++ ) cc=${GCXX-/usr/bin/g++} ;;
  */ucgcc    ) cc=${GCC-/usr/bin/gcc}  ;;
  *          ) cc=${GCC-/usr/bin/gcc}  ;;
esac

incdir=/usr/include/uClibc
libdir=/usr/lib64/uClibc
case $* in
    *-m32* ) libdir=/usr/lib/uClibc ;;
esac

gcc_incdir=`$cc -print-libgcc-file-name`
gcc_incdir=${gcc_incdir%/*}/include

declare -a inc=(
    -nostdinc
    -isystem $incdir
    -I$gcc_incdir
)

declare -a crt=(
    -nostartfiles
    -nodefaultlibs
    -nostdlib

    $libdir/crt1.o
    $libdir/crti.o

    -L$libdir
)

declare -a lib=(
    $libdir/libm.a
    $libdir/libc.a
    $libdir/crtn.o
)

declare -a ccargs=()
while [ $# -gt 0 ]; do
    ccargs+=( "$1" )

    elt=$1
    shift

    case $elt in
        --version ) inc=() crt=() lib=() ;;
        -[cSE] )           crt=() lib=() ;;
        -o     )
            case $1 in
                *.l[ao] )  crt=() lib=() ;;
            esac
    esac
done


exec $cc "${inc[@]}" "${crt[@]}" "${ccargs[@]}" "${lib[@]}"

# eof
