#!/bin/bash

declare -a client_args=()
declare -a server_args=()

deffirst()
{
    local var=$1 ; shift
    local file

    case ${!var-notset} in
        notset )
            for file in "$@"; do
                if test -f "$file"; then
                    eval export $var=\""$file"\"
                    return 0
                fi
            done
            return 1 ;;
    esac
    return 0
}

find_free_display()
{
    let i=0
    while :; do
        if [ -e /tmp/.X$i-lock ] || [ -S /tmp/.X11-unix/X$i ]; then
            if ! grep -q -s /tmp/.X11-unix/X$i /proc/net/unix; then
                break
            fi
        else
            break
        fi
        i=$(( $i + 1 ))
        test -e /tmp/.X${i}-lock && continue
    done
    NewDisplay=:$i
}

get_client_server_args()
{
    while [ $# -gt 0 ]; do
        case $1 in
            -- ) shift; break ;;
        esac
        client_args+=( "$1" )
        shift
    done

    while [ $# -gt 0 ]; do
        case $1 in
            :[0-9]* ) NewDisplay=$1 ;;
        esac
        server_args+=( "$1" )
        shift
    done

    case ${NewDisplay:-notset} in
        notset ) find_free_display
                 server_args=( $NewDisplay "${server_args[@]}" )
                 ;;
    esac
}

main()
{
    get_client_server_args "$@"

    sinit=${sinit-$HOME/etc/init}

    deffirst XINITRC   $HOME/.xinitrc   $sinit/share/xinitrc
    deffirst XSERVERRC $HOME/.xserverrc $sinit/share/xserverrc

    exec run-next "$0" "${client_args[@]}" -- "${server_args[@]}"
}

main "$@"

# eof
